name: Java CI with Maven by Ekan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: trigger jenkins Job
      uses: kannex/jenkins-action@master
      with:
        url: "http://172.20.10.5:8080"
        user: "admin"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "TomcatDeployment"
    

  
